import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'
import Provider from '@/components/Provider'
import { ThemeProvider } from '@/components/theme-provider'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main className="max-w-5xl w-full px-4 mx-auto min-h-screen">
              <Header />
              {children}
            </main>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
